'''
Hylaa File I/O Logic
May 2017
Stanley Bak
'''

def write_matlab(filename, poly_data_dict, plot_settings, ha):
    'save the polygon data to a matlab script'

    with open(filename, 'w') as f:

        # header
        f.write('''% Plot reachable region (Code generated by Hylaa using PLOT_MATLAB)
h = figure(1);
set(h, 'Position', [200 200 800 600]);
hold on;

% data
reachSet = [
''')

        # data
        for name, data in poly_data_dict.iteritems():
            fcol, ecol, polys = data
            f.write("    {{'{}', [{} {} {}], [{} {} {}], 0, {{\n".format(name, fcol[0], fcol[1], fcol[2], ecol[0], ecol[1], ecol[2]))

            #[-3, 0; -3, 1; -4, 1; -3.5 0.5;-4, 0]
            for poly in polys:
                f.write("    [")

                for pt in poly:
                    f.write("{}, {};".format(pt[0], pt[1]))
                
                f.write("]\n")
            
            f.write("    }}\n")
            
        f.write('''];

% plot all
for i = 1:size(reachSet,1)
    face_color = reachSet{i,2};
    edge_color = reachSet{i,3};
    poly_list = reachSet{i,5};

    for p_index = 1:size(poly_list,1)
        pts = poly_list{p_index};
        h = fill(pts(:,1), pts(:,2), face_color, 'EdgeColor', edge_color);

        reachSet{i,4} = h;  % add handle to reachSet data structure for use in legend
    end
end

% optional legend
if (size(reachSet,1) > 1 && size(reachSet,1) < 10)
    legend([reachSet{:,3}], reachSet{:,1})
end

% labels and such
''')


        l = plot_settings.label
        x_label = l.x_label if l.x_label is not None else ha.variables[plot_settings.xdim].capitalize()
        y_label = l.y_label if l.y_label is not None else ha.variables[plot_settings.ydim].capitalize()
        title = l.title if l.title is not None else ha.name
        
        f.write("xlabel('{}', 'FontSize', {}, 'FontName', 'Serif', 'Interpreter','LaTex');\n".format(x_label, l.label_size))
        f.write("ylabel('{}', 'FontSize', {}, 'FontName', 'Serif', 'Interpreter','LaTex');\n".format(y_label, l.label_size))
        f.write("title('{}', 'FontSize', {}, 'FontName', 'Serif', 'Interpreter','LaTex');\n".format(title, l.title_size))

        f.write("hold off;\n")
